# Open WebUI Deployment for Llama 4 vLLM
# Provides a ChatGPT-style web interface for interacting with Llama 4 model
#
# Usage:
#   kubectl apply -f open-webui.yaml
#   kubectl port-forward -n open-webui svc/open-webui 8080:80
#   Open http://localhost:8080 in your browser

---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # Connect to Llama 4 vLLM service via Kubernetes DNS
        - name: OPENAI_API_BASE_URLS
          value: "http://llama4-vllm-svc.llama4-vllm.svc.cluster.local:8000/v1"
        - name: OPENAI_API_KEY
          value: "dummy"
        # Disable Ollama integration (using OpenAI-compatible API only)
        - name: OLLAMA_BASE_URL
          value: ""
        - name: WEBUI_AUTH
          value: "true"
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: webui-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
