# Open WebUI Deployment for Llama 4 on Trainium2
# Provides a ChatGPT-style interface to interact with Llama 4 models
#
# Usage:
#   kubectl apply -f open-webui.yaml
#   kubectl -n open-webui port-forward svc/open-webui 8080:80
#   Open http://localhost:8080 in your browser

---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/name: open-webui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        # Connect to Llama 4 Scout on Trainium2
        - name: OPENAI_API_BASE_URLS
          value: "http://llama4-vllm-trn2-svc.llama4-vllm.svc.cluster.local:8000/v1"
        - name: OPENAI_API_KEYS
          value: "not-needed"
        - name: WEBUI_AUTH
          value: "true"
        - name: WEBUI_NAME
          value: "Llama 4 on Trainium2"
        - name: DEFAULT_MODELS
          value: "meta-llama/Llama-4-Scout-17B-16E-Instruct"
        - name: ENABLE_OLLAMA_API
          value: "false"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: data
          mountPath: /app/backend/data
      volumes:
      - name: data
        emptyDir:
          sizeLimit: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
